name: Rust

on:
  push:
    branches:
      - 'master'
      - '!gh-pages'
  pull_request:

jobs:
  build:
    runs-on: ${{ matrix.os }}
    env:
      RUST_BACKTRACE: 1
    strategy:
      fail-fast: false
      matrix:
        build: [linux64, linux32, macos, win64]
        include:
          - build: linux64
            os: ubuntu-latest
            target: x86_64-unknown-linux-gnu
          - build: linux32
            os: ubuntu-latest
            target: i686-unknown-linux-gnu
          - build: macos
            os: macos-latest
            target: x86_64-apple-darwin
          - build: win64
            os: windows-latest
            target: x86_64-pc-windows-msvc
    steps:
      - uses: actions/checkout@v2
      - name: Install g++-multilib
        run: |
          set -e
          # Remove the ubuntu-toolchain-r/test PPA, which is added by default.
          # Some packages were removed, and this is causing the g++multilib
          # install to fail. Similar issue:
          # https://github.com/scikit-learn/scikit-learn/issues/13928.
          sudo add-apt-repository --remove ppa:ubuntu-toolchain-r/test
          sudo apt-get install g++-multilib
        shell: bash
        if: matrix.build == 'linux32'
      - run: |
          rustup toolchain install nightly-${{ matrix.target }}
          rustup default nightly-${{ matrix.target }}
      - run: cargo build
      - run: |
          ulimit -n 16
          cargo run
