name: Rust

on:
  push:
    branches:
      - 'master'
      - '!gh-pages'
  pull_request:

jobs:
  build:
    runs-on: ${{ matrix.os }}
    env:
      RUST_BACKTRACE: 1
    strategy:
      fail-fast: false
      matrix:
        build: [linux64, linux32, macos, win64]
        include:
          - build: linux64
            os: ubuntu-latest
            target: x86_64-unknown-linux-gnu
          - build: macos
            os: macos-latest
            target: x86_64-apple-darwin
    steps:
      - uses: actions/checkout@v2
      - run: |
          rustup toolchain install nightly-${{ matrix.target }}
          rustup default nightly-${{ matrix.target }}
      - run: cargo build
      - run: |
          ulimit -n 16
          cargo run
        shell: bash
